language: node_js
node_js: '8'
cache:
  yarn: true
install:
- yarn --frozen-lockfile --non-interactive
stages:
- name: test
  if: "(tag IS blank) OR (type != push) OR (repo != dkushner/bureau)"
- name: deploy
  if: "(tag IS present) AND (type = push) AND (repo = dkushner/bureau)"
jobs:
  include:
  - stage: test
    before_script:
    - npm i codecov -g
    script:
    - yarn run lint
    - yarn run test:coverage
    - yarn run build
    after_script:
    - codecov
  - stage: deploy
    before_script:
    - npm i codecov -g
    script:
    - yarn run lint
    - yarn run test:coverage && codecov
    - yarn run build
    - rm -rf release && mkdir -p release
    - for file in ./_bundles/*; do cp "$file" "${file/lib\/bureau/release/bureau-${TRAVIS_TAG}}"; done
    - zip -jr "release/bureau-${TRAVIS_TAG}.zip" release/*
    deploy:
    - provider: npm
      email: root@davidkushner.me
      api_key: "$NPM_API_KEY"
      tag: beta
      skip_cleanup: true
      on:
        repo: dkushner/bureau
        tags: true
    - provider: releases
      api_key: "$GITHUB_API_KEY"
      file: release/bureau-${TRAVIS_TAG}.zip
      skip_cleanup: true
      on:
        repo: dkushner/bureau
        tags: true
